/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TebakAngkaWindow extends javax.swing.JFrame {
    int angkaSoal;

    /**
     * Creates new form TebakAngkaWindow
     */
    public TebakAngkaWindow() {
        initComponents();
        inputAngkaTextField.setVisible(false);
        cekAngkaButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        petunjukLabel = new javax.swing.JLabel();
        inputAngkaTextField = new javax.swing.JTextField();
        cekAngkaButton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/tebakAngka.jpg"))); // NOI18N

        startButton.setBackground(new java.awt.Color(255, 255, 0));
        startButton.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        petunjukLabel.setFont(new java.awt.Font("Bernard MT Condensed", 0, 12)); // NOI18N
        petunjukLabel.setText("Klik tombol start !");

        inputAngkaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAngkaTextFieldActionPerformed(evt);
            }
        });

        cekAngkaButton.setBackground(new java.awt.Color(255, 255, 0));
        cekAngkaButton.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        cekAngkaButton.setText("ARE YOU SURE?");
        cekAngkaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekAngkaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputAngkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(startButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(petunjukLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(cekAngkaButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(petunjukLabel)
                .addGap(18, 18, 18)
                .addComponent(inputAngkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekAngkaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        angkaSoal = generateAngka();
        petunjukLabel.setText("Masukan angka 1 - 100 !");
        startButton.setVisible(false);
        inputAngkaTextField.setVisible(true);
        cekAngkaButton.setVisible(true);
    }//GEN-LAST:event_startButtonActionPerformed

    private void inputAngkaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAngkaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAngkaTextFieldActionPerformed

    int jawaban = 0;
    
    private void cekAngkaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekAngkaButtonActionPerformed
        // TODO add your handling code here:
        jawaban++;
        try{
            String tebakanString = inputAngkaTextField.getText();
            int tebakan = Integer.parseInt(tebakanString);
            if(tebakan == angkaSoal){
                petunjukLabel.setText("Brilliant! Anda menang setelah " +  jawaban + "kali menjawab !");
            }
            else{
                String message;

                if(angkaSoal > tebakan){
                    message = "Jawaban terlalu kecil. Coba lebih besar. Jawaban terakhir : "+inputAngkaTextField.getText()+"." ;
                    inputAngkaTextField.setText("");
                }else 
                {
                    message = "Jawaban terlalu besar. Coba lebih kecil. Jawaban terakhir : "+inputAngkaTextField.getText()+".";
                    inputAngkaTextField.setText("");
                }
                petunjukLabel.setText(message);
            }
        }

        catch (Exception e){
            //petunjukLabel.setText("Harus diisi dengan angka!");
            JOptionPane.showMessageDialog(rootPane, "Hanya bisa diisi dengan angka !");
        }

    }//GEN-LAST:event_cekAngkaButtonActionPerformed

    private int generateAngka(){
        double random = Math.random() * 100;
        double ceilValue = Math.ceil(random);
        int generatedAngkaSoal = (int) ceilValue;
        return generatedAngkaSoal;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakAngkaWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekAngkaButton;
    private javax.swing.JTextField inputAngkaTextField;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel petunjukLabel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
